version: '3.8'
services:
   health_management_container:
    container_name: health_management_container
    build: ./
    tty: true
    privileged: true
    volumes:
      - ./health_management_container:/phm_tool
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /dev:/dev #Devices
    environment:
      - CONTAINER_TO_MONITOR=ros_app_container
      - ROS_MASTER_URI=http://ros_app_container:11311
    user: root
    networks:
      - my_network  

networks:
  my_network:
    external: true 
