version: '3.8'
services:
   containera:
     container_name: containera
     build: ./Application_Container
     volumes:
       - ./Application_Container:/app
     ports:
      - "4000:80"
     environment:
      - ROS_MASTER_URI=http://containera:11311
     networks:
      - rosnet

   containerb:
    container_name: containerb
    build: ./PHM_Container
    volumes:
       - ./PHM_Container:/phm_tool
       - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINER_TO_MONITOR=containera
      - ROS_MASTER_URI=http://containera:11311
    depends_on:
      - containera
    networks:
      - rosnet
    user: root
    command: ["python3", "tests.py"]

networks:
  rosnet:
    driver: bridge
