version: '3.8'
services:
   application_container:
     container_name: application_container
     build: ./application_container
     volumes:
       - ./application_container:/app
     ports:
      - "4000:80"
     environment:
      - ROS_MASTER_URI=http://application_container:11311
     networks:
      - rosnet

   health_managment_container:
    container_name: health_managment_container
    build: ./health_managment_container
    volumes:
       - ./health_managment_container:/phm_tool
       - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINER_TO_MONITOR=application_container
      - ROS_MASTER_URI=http://application_container:11311
    depends_on:
      - application_container
    networks:
      - rosnet
    user: root

networks:
  rosnet:
    driver: bridge
